version: '2'

services:
  my-team-api:
       build:
          context: ../../.
          dockerfile: ./docker/development/Dockerfile
          args:
            - env=local
       volumes:
         - ../../api/.:/api/
         - /sys/fs/cgroup:/sys/fs/cgroup:ro
         - /etc/localtime:/etc/localtime
       container_name: my-team-api
       environment:
         - APP_ENV=local
         - TERM=xterm-256color
       privileged: true
       expose:
         - "80"
       ports:
         - "80:80"
       depends_on: 
         - my-team-api-db
       links:
         - my-team-api-db    
  my-team-api-db:
    image: mysql
    container_name: my-team-api-db
    volumes:
      - ../../mysql-data:/var/lib/mysql
    expose: 
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE= myteamcsgo